export const specializations = [
  "Cardiology",
  "Dermatology",
  "Endocrinology",
  "Gastroenterology",
  "Neurology",
  "Oncology",
  "Pediatrics",
  "Psychiatry",
  "Radiology",
  "Surgery",
];

export const concepts = [
  "JSX",
  "Clean Folder Structure",
  "Toastify",
  "API Creation",
  "backdrop-filter",
  "Bearer Token",
  "useState()",
  "Form Validation",
  "Hooks",
  "Lifecycle Methods",
  "C#",
  "Event Handling",
  "Conditional Rendering",
  "Splitting Code",
  "BrowserRouter",
  "Session Storage",
  "Dependency Injection",
  "Context API",
  "CSS designing",
  "Promise Architecture",
  "MVC",
  "Asynchronous Programming",
  "useEffect()",
  "Props",
  "Web API",
  "Require()",
  ":hover",
  "Spread Operator",
  ".NET Core",
];
